# BREV Launchable Configuration for Kit App 108.1
# This file defines the deployment settings for NVIDIA Brev

launchable:
  name: "Omniverse Kit App 108.1 USD Composer"
  description: "Cloud-based USD authoring with Omniverse Kit App 108.1 and WebRTC streaming"
  version: "1.0.0"
  author: "jph2_company"

compute:
  gpu_type: "L40S"  # Minimum GPU for port access (T4/L4 lacks drivers)
  cloud_provider: "AWS"  # Required for port access, other providers often block ports
  cpu_cores: 4
  memory_gb: 32
  disk_gb: 100

container:
  image: "nvcr.io/nvidia/isaac-sim:5.0.0"
  ports:
    - 80      # nginx (VSCode Server proxy)
    - 8080    # VSCode Server (internal)
    - 1024    # WebRTC signaling (required for viewer)
    - 3000    # WebRTC viewer
    - 49100   # Kit App WebRTC
    - 47998   # WebRTC streaming

environment:
  ACCEPT_EULA: "Y"
  OMNIVERSE_KIT_APP: "jph2_company.jph2_usd_composer"
  KIT_EXTENSIONS_PATH: "/workspace/extensions"

setup_script: |
  #!/bin/bash
  echo "Setting up Kit App 108.1 Launchable..."
  
  # Clone the repository
  git clone https://github.com/jph2/Kit-app-108.1-Launchable.git
  cd Kit-app-108.1-Launchable/kit-app-108
  
  # Run setup script to create necessary files
  chmod +x setup.sh
  ./setup.sh
  
  # Start the containers
  docker-compose up -d
  
  echo "Kit App 108.1 Launchable setup complete!"

requirements:
  - Docker
  - NVIDIA Container Toolkit
  - Git
